export const FETCH_LOCATION_PROGRESS = 'FETCH_LOCATION_PROGRESS';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILURE = 'FETCH_LOCATION_FAILURE';
export const SET_LOCATION = 'SET_LOCATION';